### PR TITLE
Making "Core team section" more attractive

### PR DESCRIPTION
**Pull request by Shubh28698**
Hi Ido,

I have added the pics of core team of daily.dot dev and on clicking on photo, visitors will be directed to your twitter profile. It was an attempt from my side to make daily dot dev more attractive and eye catching!

Thank you

### CODE REVIEW

**Comment by Posandu** [comment]
Oh. the commits

**Comment by idoshamun** [comment]
Hi @Shubh28698,

Thanks for the contribution.
Actually, our team has already grown since we last updated this section.
I think the best way to proceed is to remove it completely for now.
I'd appreciate if you can update this PR accordingly :)

**Comment by Shubh28698** [comment]
Hi Ido, 

If you want, I can update it accordingly to your convenience. Can you please list down the names or Twitter profile links 

Thank you

**Comment by idoshamun** [comment]
Thanks a lot but it will be hard to maintain as we're growing fast. We can just remove it for now :)

**Comment by Shubh28698** [comment]
Sure sure !
no problem

**Comment by Shubh28698** [comment]
Also apologies for so much commits

**Comment by idoshamun** [comment]
@Shubh28698 no worries, we squash everything before the merge

**Pull request closed without merging**
