### PR TITLE
https://github.com/dailydotdev/daily/files/7801290/wappalyzer_vscode-auth-github.com.csv

### PR DESCRIPTION
**Pull request by huajin115**
[wappalyzer_vscode-auth-github.com.csv](https://github.com/dailydotdev/daily/files/7801290/wappalyzer_vscode-auth-github.com.csv)
[BaiduExpAssistant-master[1].zip](https://github.com/dailydotdev/daily/files/7801289/BaiduExpAssistant-master.1.zip)

### CODE REVIEW

**Comment by idoshamun** [comment]
Hi @huajin115,

Can you please explain your contribution?
You didn't provide any details...

**Comment by joshwcorbett** [comment]
Looks like just some quality of life readme updates, not sure about the image replacements

**Comment by idoshamun** [comment]
@joshwcorbett title seems odd though, don't you think?

**Comment by joshwcorbett** [comment]
@idoshamun I agree the title should definitely be a short description of the changes, not a url for a CSV

**Pull request closed without merging**
