### PR TITLE
Added Microsoft Edge to extensions

### PR DESCRIPTION
**Pull request by max-programming**
I noticed that MS Edge extension was missing in the list of extensions.
So I added it

### CODE REVIEW

**Comment by max-programming** [comment]
Also the number of users is remaining of MS Edge. I wasn't able to add it as I was not able to find it out

image

**Review by idoshamun — APPROVED** [review]
Wow! Thanks for noticing this and contributing this fix 🤩

**Comment by max-programming** [comment]
One more thing @idoshamun . Make the word `respository` - `repository`.
image

And also, if possible add the MS Edge Addons user count like the Chrome web store and FF Addons

**Comment by idoshamun** [comment]
Thanks @max-programming, I fixed the typo.
Unfortunately, user count is no longer supported in Chrome so I removed these badges completely

**Comment by max-programming** [comment]
Are you talking about these?
image

**Comment by idoshamun** [comment]
Oh, sorry I was confused with the user's rating badge that is no longer supported.
I'll check if there is a badge for Edge as well.

**Comment by idoshamun** [comment]
I can't find anything related here:
https://shields.io/

**Comment by max-programming** [comment]
> I can't find anything related here:
> https://shields.io/

Maybe you can leave it. It's fine I guess. If I find it. I will make another PR.

**Comment by idoshamun** [comment]
Feel free! We always welcome any contribution ✨

**Pull request merged**
